name = "aerialdb"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".svelte-kit/cloudflare"

# Production D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "aerialdb-production"
database_id = "694fa60c-9e1d-404d-aa49-26365e7365bf"

# Production R2 Bucket binding for image storage
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "aerialdb-images"

# Preview (dev) environment overrides
[[env.preview.d1_databases]]
binding = "DB"
database_name = "aerialdb-dev"
database_id = "69f5961f-8d79-4c8d-8383-c3dabcc98242"

[[env.preview.r2_buckets]]
binding = "IMAGES"
bucket_name = "aerialdb-images-dev"
